
package sistemaventas;

import java.sql.*;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import Conexion.ClassConection;
public class Boleta extends javax.swing.JInternalFrame {
 Connection cn;
   CallableStatement cts;
   ResultSet r;
   ClassConection conectar=new ClassConection();
    public Boleta() {
        initComponents();
        
          cn=conectar.conecion();
          
          Calendar cal=Calendar.getInstance();
            String fecha=cal.get(Calendar.DATE)+"/"+cal.get(Calendar.MONTH)+"/"+cal.get(cal.YEAR);
            this.jlb_Fecha.setText(fecha);
            try{
        
         cts=cn.prepareCall("{call Genera_num_BOLETAS}");
       r=cts.executeQuery();
       if (r.next())
        
          jTextField1.setText(r.getString(1));
            }catch (Exception e){} 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_detalleboleta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jlb_senores = new javax.swing.JLabel();
        jlb_dni = new javax.swing.JLabel();
        jlb_Fecha = new javax.swing.JLabel();
        jlb_codclie = new javax.swing.JLabel();
        jlb_direccion = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("Total a Pagra:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 16, -1, -1));

        jTextField6.setEditable(false);
        jPanel4.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 13, 79, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 166, 652, 40));

        jta_detalleboleta.setBackground(new java.awt.Color(102, 255, 204));
        jta_detalleboleta.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        jta_detalleboleta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRIPCION", "CANTIDAD", "PRECIO UNITARIO", "PRECIO VENTA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jta_detalleboleta);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 652, 147));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 263, 670, 220));

        jLabel2.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RESTAURANT ANTHONY");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 222, -1));

        jLabel4.setText("Jron 13 De Diciembre N° 176");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jLabel3.setText("Marco Antonio Vargas Mendez");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel5.setText("Teléfono: 957552985");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        jLabel6.setText("Señor(es):");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 135, -1, -1));

        jLabel7.setText("DNI:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 165, -1, -1));

        jLabel8.setText("Cod.Cliente:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 165, -1, -1));

        jLabel9.setText("Fecha:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 165, -1, -1));

        jLabel10.setText("Direccion:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 199, -1, -1));

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 135, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("ARTICULOS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 147, 43));

        jButton3.setText("CALCULAR OPERACION");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 62, -1, 37));

        jButton4.setText("ELIMINAR ARTICULO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 105, 147, 38));

        jButton5.setText("REALIZAE VENTA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 149, 147, 37));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 279, 170, 200));

        jlb_senores.setForeground(new java.awt.Color(0, 153, 153));
        jlb_senores.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jlb_senores, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 139, 330, 19));

        jlb_dni.setForeground(new java.awt.Color(0, 153, 153));
        jlb_dni.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jlb_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 165, 112, 19));

        jlb_Fecha.setForeground(new java.awt.Color(0, 153, 153));
        jlb_Fecha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jlb_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 165, 90, 19));

        jlb_codclie.setForeground(new java.awt.Color(0, 153, 153));
        jlb_codclie.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jlb_codclie, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 165, 62, 19));

        jlb_direccion.setForeground(new java.awt.Color(0, 153, 153));
        jlb_direccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jlb_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 194, 385, 19));

        jPanel5.setBackground(new java.awt.Color(153, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BOLETA DE VENTA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("R.U.C.:20248454753");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 57, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("N°:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 112, -1, -1));

        jTextField1.setEnabled(false);
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 112, 147, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 93, 320, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         BuacarClienteB bc=new  BuacarClienteB ();
        SistemaV.jDesktopPane1.add(bc);
        bc.toFront();
        bc.setLocation(50,10);
        bc.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        try {
            BuscarArticulosB bs= new BuscarArticulosB();
            SistemaV.jDesktopPane1.add(bs);
        bs.toFront();
        bs.setLocation(50,10);
        bs.setVisible(true);
        
        } catch (Exception ex) {
            Logger.getLogger(Factura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        agregarBoletos();
        agregarDETALLEBoletos();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         double suma=0.0;
         double subtot=0.0;
        
             for(int i=0;i<jta_detalleboleta.getRowCount();i++){
            String precio= jta_detalleboleta.getValueAt(i, 3).toString();
          String cantidad=jta_detalleboleta.getValueAt(i , 2).toString();
          int c=Integer.parseInt(cantidad);
          double p=Double.parseDouble(precio);
          suma=c*p;
             subtot+=suma;    
           
            jta_detalleboleta.setValueAt(suma, i, 4);
             jTextField6.setText(""+subtot);
                        
             
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
         javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jta_detalleboleta.getModel();
        //ahora obtenemos la fila selccionada
        int fila_select = jta_detalleboleta.getSelectedRow();

        if(fila_select<0){
            // no se puede eliminar
            JOptionPane.showMessageDialog(this,"Tabla vacia o no ha seleccionado uan fila.");
        }else {
          // la eliminamos del modelo:
        modelo.removeRow(fila_select);
        }

    }//GEN-LAST:event_jButton4ActionPerformed
public void agregarBoletos(){
        String nBO=jTextField1.getText();
        String fec=jlb_Fecha.getText();
        String codcli=jlb_codclie.getText();
        String tot=jTextField6.getText().toString();
        
        try {
            cts=cn.prepareCall("{call InsertaBOLETOS(?,?,?,?)}");
            cts.setString(1, nBO);
            cts.setString(2,fec);
            cts.setString(3, codcli);
            cts.setString(4, tot);
            int opcion=cts.executeUpdate();
            if(opcion==1)
                JOptionPane.showMessageDialog(this, "Boleta registrada coreectamente","Aviso",JOptionPane.INFORMATION_MESSAGE);
                     
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error al registrar");
        }
}
public void agregarDETALLEBoletos(){
     for(int i=0;i<jta_detalleboleta.getRowCount();i++){
         String nbol=jTextField1.getText();
        String codpro=jta_detalleboleta.getValueAt(i,0).toString();
        String prod=jta_detalleboleta.getValueAt(i,1).toString();
        String cant=jta_detalleboleta.getValueAt(i,2).toString();
        String pre_u=jta_detalleboleta.getValueAt(i,3).toString();
        String pre_v=jta_detalleboleta.getValueAt(i,4).toString();
        
        try{
            cts=cn.prepareCall("{call INSERTADETALLEBOLETO(?,?,?,?,?,?)}");
            cts.setString(1, nbol);
            cts.setString(2, codpro);
            cts.setString(3, prod);
            cts.setString(4, cant);
            cts.setString(5, pre_u);
            cts.setString(6, pre_v);
            
            int opcion=cts.executeUpdate();
            if (opcion==1)
                JOptionPane.showMessageDialog(this, "Registrado correctamente!!","aviso",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error al registrar"+e.getMessage());
                
        }}
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField6;
    public static javax.swing.JLabel jlb_Fecha;
    public static javax.swing.JLabel jlb_codclie;
    public static javax.swing.JLabel jlb_direccion;
    public static javax.swing.JLabel jlb_dni;
    public static javax.swing.JLabel jlb_senores;
    public static javax.swing.JTable jta_detalleboleta;
    // End of variables declaration//GEN-END:variables
}
